name: vibespot
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # material_design_icons_flutter: ^2.7.94
  # community_material_icon: ^0.1.2
  groovin_material_icons: ^1.0.5

  sqflite: 0.11.2+2
  path_provider: ^0.4.1
  http: ^0.12.0
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/splash.png
   - assets/images/splash-background.png
   - assets/images/vibe-logo-on-splash-background.png
   - assets/images/vibe-logo-on-black.png
   - assets/images/create-account-btn.png
   - assets/images/signin-btn.png
   - assets/images/email-btn.png
   - assets/images/facebook-btn.png
   - assets/images/google-btn.png
   - assets/images/email-icon.png
   - assets/images/facebook-white-logo.png
   - assets/images/google-white-logo.png
   - assets/images/mySpot-selected-icon.png
   - assets/images/vibeStream-selected-icon.png
   - assets/images/vibespot-appicon2x.png
   - assets/images/no-data-image.png
   - assets/images/shopping-cart-icon.png
   - assets/images/shape2-icon.png
   - assets/images/add-plus-icon.png
   - assets/images/myAccount-selected-icon.png

   

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: italic

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# fonts:
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Italic.ttf
#           weight: 200
#       fonts: 
#         - asset: assets/fonts/Poppins-Bold.ttf
#           weight: 100
#       fonts: 
#         - asset: assets/fonts/Poppins-Regular.ttf
#           weight: 400


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
